# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwNy5J33wNBAqKnbPekQfdx7lF9YsC-c
"""

import streamlit as st
from google import genai
from rag import load_collection, ask_rbi

st.set_page_config(
    page_title="RBI GPT",
    page_icon="🏦",
    layout="centered"
)

st.title("🏦 RBI GPT")
st.caption("Ask anything about RBI Master Circulars")

@st.cache_resource
def setup():
    collection = load_collection("rbi_db")
    gemini_client = genai.Client(api_key=st.secrets["GEMINI_API_KEY"])
    return collection, gemini_client

collection, gemini_client = setup()

if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

simple_mode = st.toggle("Simple explanation mode (for non-bankers)")

if prompt := st.chat_input("Ask an RBI question..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Searching RBI circulars..."):
            try:
                answer = ask_rbi(collection, gemini_client, prompt, simple=simple_mode)
                st.markdown(answer)
                st.session_state.messages.append({"role": "assistant", "content": answer})
            except Exception as e:
                st.error(f"Error: {str(e)}")