# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwNy5J33wNBAqKnbPekQfdx7lF9YsC-c
"""

import chromadb
from sentence_transformers import SentenceTransformer
from google import genai

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

def load_collection(db_path="rbi_db"):
    chroma_client = chromadb.PersistentClient(path=db_path)
    collection = chroma_client.get_or_create_collection(name="rbi_master_circulars")
    return collection

def search_rbi(collection, question, k=20):
    question_embedding = embedding_model.encode(question).tolist()
    results = collection.query(
        query_embeddings=[question_embedding],
        n_results=k,
        include=["documents", "metadatas", "distances"]
    )
    return results

def ask_rbi(collection, gemini_client, question, simple=False):
    results = search_rbi(collection, question)
    context_parts = []
    for doc, meta in zip(results["documents"][0], results["metadatas"][0]):
        context_parts.append(f"[Source: {meta['title']}]\n{doc}")
    context = "\n\n".join(context_parts)

    if simple:
        tone = "Explain in simple, plain language that a non-banker can understand. Avoid jargon."
    else:
        tone = "Use precise regulatory language suitable for banking professionals."

    prompt = f"""You are an RBI regulatory assistant.
Answer ONLY using the provided RBI context below.
{tone}
Always mention which circular the answer comes from.
If the answer is not present in the context, say:
'The information is not available in the retrieved RBI documents.'

Context:
{context}

Question:
{question}
"""
    response = gemini_client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )
    return response.text